//! Who somebody is, as against which seat they are sitting in.
//!
//! [`PlayerId`] is a seat: four bits in a cell, one to fifteen, per world, and
//! handed to whoever fills the room next. A rejoin token is a seat's claim
//! ticket, filed per room, and a match *is* a room — so a number kept against
//! a token is earned in a match and thrown away with it. Neither of them is a
//! person, and a rating is a fact about a person.
//!
//! So a **person is a keypair**, generated by the client and never sent. The
//! public half is the id: it is what a rating table is keyed by and what a
//! leaderboard would show, and handing it to somebody lets them name you and
//! not be you. The private half never leaves the machine it was made on.
//!
//! ## Why the client issues it, and why that forces a signature
//!
//! A server-minted bearer secret was the first answer and it works exactly as
//! long as identity stays per server. The moment the same key is meant to mean
//! the same person on **several** servers, a bearer secret becomes the wrong
//! shape twice over. It has to be sent to be checked, so every server you
//! visit learns a credential that is valid at every other one — a server you
//! played on once can be you everywhere. And a server that has never seen your
//! id has no way to tell you from somebody claiming it, so the first machine
//! to present an id anywhere owns it there, and an id is public by design.
//!
//! A signature answers both. Joining is: the server offers a challenge, the
//! client signs it, and the server knows it is talking to whoever holds that
//! key without ever having issued anything and without learning anything it
//! could reuse. The challenge is *that server's*, so a signature captured by
//! one server is worthless at another.
//!
//! It also empties the server's table of secrets. [`crate::server::people`]
//! records who has been seen; there is nothing in it worth stealing.
//!
//! ## Losing it
//!
//! Whoever holds the private half is you, and nobody can give it back. There
//! is no account behind it and no address to send a reset to. That is the
//! honest cost of nobody being able to take it from you, and it should be said
//! on screen rather than discovered — see [`Key::written`], which is the only
//! thing here that ever produces the secret half as text.
//!
//! [`PlayerId`]: crate::sim::PlayerId

use ed25519_dalek::{Signature, Signer, SigningKey, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};

/// Bytes in the seed a signing key is built from, and in a public key.
const SEED_N: usize = 32;

/// What a key file says it is for, in the place OpenSSH puts an email address.
const COMMENT: &str = "conwayskingdom";

/// The public half: who somebody is.
///
/// Shown, stored against results, and safe to hand out. An ed25519 public key
/// as hex, which is what makes it the same name on every server without any of
/// them agreeing to anything.
#[derive(Clone, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct PersonId(pub String);

impl PersonId {
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// The key this names, or nothing if it is not one.
    fn verifying(&self) -> Option<VerifyingKey> {
        VerifyingKey::from_bytes(&unhex::<SEED_N>(&self.0)?).ok()
    }
}

impl std::fmt::Display for PersonId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

/// A claim to be somebody, good for exactly one challenge.
///
/// What crosses the wire on a join. The id is public and the signature says
/// the sender holds the other half of it — over **the server's** challenge, so
/// this is worth nothing to anybody else who sees it.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct Claim {
    pub id: PersonId,
    /// The signature over the challenge, as hex.
    pub signature: String,
}

impl Claim {
    /// Whether this really is that person, answering that challenge.
    ///
    /// The only thing a server needs, and it needs no table to do it: a
    /// signature that checks out is the whole of the proof, whether or not
    /// this server has ever seen the id before. That is what "the client
    /// issues it" means in practice — nobody has to have handed anything out.
    pub fn verifies(&self, challenge: &str) -> bool {
        let (Some(key), Some(bytes)) = (self.id.verifying(), unhex::<64>(&self.signature)) else {
            return false;
        };
        key.verify(challenge.as_bytes(), &Signature::from_bytes(&bytes)).is_ok()
    }
}

/// A person's own key, both halves. Never sent, and never in a world.
pub struct Key(SigningKey);

impl Key {
    /// A new person, from bytes nobody else can guess.
    ///
    /// Randomness per platform rather than through one crate, because the one
    /// crate is the awkward part: `getrandom` on `wasm32-unknown-unknown`
    /// needs a feature *and* a `--cfg` flag before it will admit the browser
    /// has an entropy source. The browser's own is one call away and is a real
    /// CSPRNG, so the web takes that and native takes `getrandom`, and neither
    /// build carries the other's problem.
    pub fn new() -> Option<Self> {
        Some(Self(SigningKey::from_bytes(&seed()?)))
    }

    /// Read a key back from a file [`Self::written`] produced.
    ///
    /// Bare hex is accepted too, and only for one reason: it is what earlier
    /// builds stored, and a client that could not read its own store would
    /// silently become somebody new on the first run after an update.
    pub fn read(written: &str) -> Result<Self, String> {
        let raw = written.trim();
        if raw.contains("OPENSSH PRIVATE KEY") {
            return Ok(Self(SigningKey::from_bytes(&super::openssh::seed_of(raw)?)));
        }
        let raw = raw.to_ascii_lowercase();
        if raw.len() != SEED_N * 2 {
            return Err("that is not an OpenSSH private key file".into());
        }
        let seed = unhex::<SEED_N>(&raw).ok_or("that is not an OpenSSH private key file")?;
        Ok(Self(SigningKey::from_bytes(&seed)))
    }

    /// The key as a file, to keep somewhere and to carry to another machine.
    ///
    /// **This is the secret half**, and it has to be: a public key proves
    /// nothing without the private one behind it, so there is no weaker thing
    /// to export that would still be you at the far end. Whoever holds this is
    /// you, everywhere, for ever — which is the same bargain as the rejoin
    /// token and a much bigger one, since it is scoped to neither a room nor a
    /// server. Wherever it is shown, that sentence goes with it.
    ///
    /// OpenSSH's format rather than bare hex, because the point of it being a
    /// file is that it is a *recognisable* one — `ssh-keygen -y` reads it, a
    /// password manager will hold it beside the others, and it looks like
    /// something to keep rather than a string to paste over.
    pub fn written(&self) -> String {
        super::openssh::private(&self.0.to_bytes(), self.0.verifying_key().as_bytes(), COMMENT)
    }

    /// The public half as an `authorized_keys` line: the same 32 bytes the id
    /// is, said in a way people recognise.
    pub fn public(&self) -> String {
        super::openssh::public(self.0.verifying_key().as_bytes(), COMMENT)
    }

    /// Who this is, publicly.
    pub fn id(&self) -> PersonId {
        PersonId(hex(self.0.verifying_key().as_bytes()))
    }

    /// Answer a server's challenge.
    pub fn claim(&self, challenge: &str) -> Claim {
        Claim { id: self.id(), signature: hex(&self.0.sign(challenge.as_bytes()).to_bytes()) }
    }
}

impl std::fmt::Debug for Key {
    /// The public half only. A key that prints itself into a log is a key in
    /// the log, and logs are copied around by people who are not thinking
    /// about what is in them.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Key({})", self.id())
    }
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn unhex<const N: usize>(text: &str) -> Option<[u8; N]> {
    if text.len() != N * 2 {
        return None;
    }
    let mut out = [0u8; N];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(text.get(i * 2..i * 2 + 2)?, 16).ok()?;
    }
    Some(out)
}

#[cfg(target_arch = "wasm32")]
fn seed() -> Option<[u8; SEED_N]> {
    let mut bytes = [0u8; SEED_N];
    web_sys::window()?.crypto().ok()?.get_random_values_with_u8_array(&mut bytes).ok()?;
    Some(bytes)
}

#[cfg(not(target_arch = "wasm32"))]
fn seed() -> Option<[u8; SEED_N]> {
    let mut bytes = [0u8; SEED_N];
    getrandom::fill(&mut bytes).ok()?;
    Some(bytes)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn key() -> Key {
        Key::new().expect("no entropy")
    }

    /// The whole of what a transfer format has to do: survive being written
    /// down and read back, so a key copied out of one browser is the same
    /// person in another — and the same person means the same id, since the id
    /// is what everything else is keyed by.
    #[test]
    fn a_key_survives_being_written_down() {
        let mine = key();
        let carried = Key::read(&mine.written()).expect("would not read back");
        assert_eq!(carried.id(), mine.id());
        assert_eq!(carried.written(), mine.written());
    }

    /// It arrives from a file picker or a clipboard, so it arrives with
    /// whatever came with it: an editor's trailing newline, Windows line
    /// endings, indentation from having been pasted into a chat window.
    #[test]
    fn a_pasted_key_file_is_forgiven_its_edges() {
        let mine = key();
        let written = mine.written();
        for messy in [
            format!("\n\n{written}\n\n"),
            format!("   {}   ", written.trim()),
            written.replace('\n', "\r\n"),
            written.lines().map(|l| format!("  {l}\n")).collect::<String>(),
        ] {
            assert_eq!(Key::read(&messy).unwrap().id(), mine.id(), "{messy:?}");
        }
    }

    /// Bare hex is still read, and for one reason: it is what earlier builds
    /// stored, and a client that could not read its own store would quietly
    /// become somebody new on the first run after an update.
    #[test]
    fn a_key_stored_before_key_files_still_reads() {
        let old = Key::read(&"a1".repeat(32)).expect("an old store was unreadable");
        assert_eq!(Key::read(&old.written()).unwrap().id(), old.id());
    }

    /// A key that is nearly one is not one. Accepting it would hand somebody
    /// an identity that is not the one they meant to bring, and they would
    /// find out when their record was empty.
    #[test]
    fn a_key_that_is_not_one_says_so() {
        let written = key().written();
        for bad in [
            String::new(),
            "hello".to_string(),
            // The armour with nothing inside it, and with rubbish inside it.
            "-----BEGIN OPENSSH PRIVATE KEY-----\n-----END OPENSSH PRIVATE KEY-----".to_string(),
            written.lines().take(2).collect::<Vec<_>>().join("\n"),
            written.replace("AAAA", "!!!!"),
        ] {
            assert!(Key::read(&bad).is_err(), "{bad:?} was accepted");
        }
    }

    /// Two people are two people. Worth asserting rather than assuming,
    /// because a seed that came back constant would be silent and would make
    /// everybody the same player.
    #[test]
    fn two_keys_are_two_people() {
        assert_ne!(key().id(), key().id());
    }

    /// The ordinary join: a challenge from the server, a signature back, and
    /// the server needs nothing it was holding beforehand to check it.
    #[test]
    fn a_claim_answers_the_challenge_it_was_made_for() {
        let mine = key();
        let claim = mine.claim("nonce-from-this-server");
        assert!(claim.verifies("nonce-from-this-server"));
        assert_eq!(claim.id, mine.id());
    }

    /// **The point of the challenge.** A signature captured by one server is
    /// worthless at another, because the other one asks a different question —
    /// which is what stops a server you played on once from being you
    /// everywhere else.
    #[test]
    fn a_claim_is_worth_nothing_to_a_different_challenge() {
        let claim = key().claim("what this server asked");
        assert!(!claim.verifies("what that server asked"));
        assert!(!claim.verifies(""));
        assert!(!claim.verifies("what this server asked "));
    }

    /// And an id is not a credential: knowing who somebody is lets you name
    /// them and never lets you be them, which is the whole reason it is safe
    /// to key a public leaderboard by it.
    #[test]
    fn holding_somebody_else_id_proves_nothing() {
        let (mine, theirs) = (key(), key());
        let forged = Claim { id: theirs.id(), signature: mine.claim("c").signature };
        assert!(!forged.verifies("c"));
        // Nor does a signature of one's own under somebody else's name.
        let mut stolen = mine.claim("c");
        stolen.id = theirs.id();
        assert!(!stolen.verifies("c"));
    }

    /// Rubbish in the signature field is a refusal, not a panic. It arrives
    /// over a wire and anybody may send anything.
    #[test]
    fn a_malformed_claim_is_refused_rather_than_fatal() {
        let id = key().id();
        for signature in ["", "zz", &"0".repeat(128), &"f".repeat(127)] {
            let claim = Claim { id: id.clone(), signature: signature.to_string() };
            assert!(!claim.verifies("c"), "{signature:?}");
        }
        let claim = Claim { id: PersonId("not a key".into()), signature: "00".repeat(64) };
        assert!(!claim.verifies("c"));
    }

    /// A key must not print itself. Logs get pasted into messages by people
    /// who are not thinking about what is in them.
    #[test]
    fn a_key_does_not_print_its_secret_half() {
        let mine = key();
        let shown = format!("{mine:?}");
        assert!(!shown.contains(&mine.written()), "the secret half was in {shown}");
        assert!(shown.contains(mine.id().as_str()));
    }
}
